### ISSUE TITLE
v0.0.1b1 PyPI Package Mismatch with GitHub

### ISSUE THREAD

**Issue by naamancampbell** [tomquirk/fajita#1]
The fajita [v0.0.1b1](https://pypi.org/project/fajita/0.0.1b1/) PyPI package contains older code and is missing the `cookie_directory` argument in fajita.py `__init__()`.

This issue also prevents using `RealestateComAu()` in [realestate-com-au-api](https://github.com/tomquirk/realestate-com-au-api).

**Comment by tmck-code** [comment]
I'm also having this issue. I this the easiest fix would just be to push the latest version of master to pypi, as the latest version of this repo works fine.
In the meantime, I managed to fix it for the `realestate-com-au-api` package by changing the `install_requires` entry in `setup.py` to point to the latest git commit hash:

```
    37      install_requires=[
    38          "requests",
    39          "fajita @ git+https://github.com/tomquirk/fajita@7b08d59"
    40      ],
```
Ref: https://github.com/tomquirk/realestate-com-au-api/blob/master/setup.py#L35

**Comment by naamancampbell** [comment]
Fixed in the latest release
